prompt_templates = {
    "Modern": "Modern-style ({room}) With bookshelves and televisions and furniture and plant and electric lamps and chairs and occasional tables and coffee tables. With Simple, Clean Lines and Simplistic Furniture and Open and Natural Lighting and Natural Materials and Elements and Neutral Walls and Textures and Practicality and Functionality and Simple, Clean Lines and Simplistic Furniture. Cinematic photo, highly detailed, cinematic lighting, ultra-detailed, ultrarealistic, photorealism, 8k. Modern interior design style",

    "Scandinavian": "Scandinavian-style ({room}) With furniture and sofa and coffee tables and electric lamps and rug and bookshelves and occasional tables and chairs. Cinematic photo, highly detailed, cinematic lighting, ultra-detailed, ultrarealistic, photorealism, 8k. Scandinavian interior design style",

    "Minimalist": "Minimalist-style ({room}) With sofa and chairs and plant and coffee tables and rug and bookshelves and furniture and occasional tables. With focus on the shape, colour and texture of just a few of essential elements and functional furniture and clean lines and an open floor plan and a monochromatic palette with colour used as an accent and lots of light and focus on the shape, colour and texture of just a few of essential elements. Cinematic photo, highly detailed, cinematic lighting, ultra-detailed, ultrarealistic, photorealism, 8k. Minimalist interior design style",

    "Boho": "bohemian-style ({room}) with carefree layers of pattern, texture, and color and lush green nature and bold colors and a lack of structure and woods and playful colors and playful textures and playful patterns. cinematic photo, highly detailed, cinematic lighting, ultra-detailed, ultrarealistic, photorealism, 8k. bohemian interior design style. masterpiece, cinematic light, ultrarealistic+, photorealistic+, 8k, raw photo, realistic, sharp focus on eyes, (symmetrical eyes), (intact eyes), hyperrealistic, highest quality, best quality, highly detailed, masterpiece, best quality, extremely detailed 8k wallpaper, ultra-detailed, best shadow, detailed background, detailed face, detailed eyes, high contrast, best illumination, dulux, caustic, dynamic angle, detailed glow, dramatic lighting, insanely detailed hair, symmetrical, professionally retouched, strong bokeh, award winning photo",

    "Industrial": "industrial-style ({room}) with reclaimed wood and exposed concrete and exposed brick and factory style and raw aesthetic and exposed rafters and metal panels and neutral tones. cinematic photo, highly detailed, cinematic lighting, ultra-detailed, ultrarealistic, photorealism, 8k. industrial interior design style. masterpiece, cinematic light, ultrarealistic+, photorealistic+, 8k, raw photo, realistic, sharp focus on eyes, (symmetrical eyes), (intact eyes), hyperrealistic, highest quality, best quality, highly detailed, masterpiece, best quality, extremely detailed 8k wallpaper, ultra-detailed, best shadow, detailed background, detailed face, detailed eyes, high contrast, best illumination, dulux, caustic, dynamic angle, detailed glow, dramatic lighting, insanely detailed hair, symmetrical, professionally retouched, strong bokeh, award winning photo",

    "Vintage": "vintage-style ({room}) cinematic photo, highly detailed, cinematic lighting, ultra-detailed, ultrarealistic, photorealism, 8k. vintage interior design style. masterpiece, cinematic light, ultrarealistic+, photorealistic+, 8k, raw photo, realistic, sharp focus on eyes, (symmetrical eyes), (intact eyes), hyperrealistic, highest quality, best quality, highly detailed, masterpiece, best quality, extremely detailed 8k wallpaper, ultra-detailed, best shadow, detailed background, detailed face, detailed eyes, high contrast, best illumination, dulux, caustic, dynamic angle, detailed glow, dramatic lighting, insanely detailed hair, symmetrical, professionally retouched, strong bokeh, award winning photo",

    "Coastal": "coastal-style ({room}) cinematic photo, highly detailed, cinematic lighting, ultra-detailed, ultrarealistic, photorealism, 8k. coastal interior design style. masterpiece, cinematic light, ultrarealistic+, photorealistic+, 8k, raw photo, realistic, sharp focus on eyes, (symmetrical eyes), (intact eyes), hyperrealistic, highest quality, best quality, highly detailed, masterpiece, best quality, extremely detailed 8k wallpaper, ultra-detailed, best shadow, detailed background, detailed face, detailed eyes, high contrast, best illumination, dulux, caustic, dynamic angle, detailed glow, dramatic lighting, insanely detailed hair, symmetrical, professionally retouched, strong bokeh, award winning photo",

    "Gaming": "gaming room-style designed ({room}) with dark room and neon letters on wall and neon lights and speakers and multiple displays and purple, red and blue fade light and computer desk with computer displays and keyboard and dark walls. cinematic photo, highly detailed, cinematic lighting, ultra-detailed, ultrarealistic, photorealism, 8k. gaming room design style. masterpiece, cinematic light, ultrarealistic+, photorealistic+, 8k, raw photo, realistic, sharp focus on eyes, (symmetrical eyes), (intact eyes), hyperrealistic, highest quality, best quality, highly detailed, masterpiece, best quality, extremely detailed 8k wallpaper, ultra-detailed, best shadow, detailed background, detailed face, detailed eyes, high contrast, best illumination, dulux, caustic, dynamic angle, detailed glow, dramatic lighting, insanely detailed hair, symmetrical, professionally retouched, strong bokeh, award winning photo",

    "Neoclassic": "baroque-style designed ({room}) with grandeur and expensive and plush flooring and intricate carvings and ornaments and opulent and colossal furniture and crystal and glass accents and tension and twisted columns and movement. cinematic photo, highly detailed, cinematic lighting, ultra-detailed, ultrarealistic, photorealism, 8k. baroque design style. masterpiece, cinematic light, ultrarealistic+, photorealistic+, 8k, raw photo, realistic, sharp focus on eyes, (symmetrical eyes), (intact eyes), hyperrealistic, highest quality, best quality, highly detailed, masterpiece, best quality, extremely detailed 8k wallpaper, ultra-detailed, best shadow, detailed background, detailed face, detailed eyes, high contrast, best illumination, dulux, caustic, dynamic angle, detailed glow, dramatic lighting, insanely detailed hair, symmetrical, professionally retouched, strong bokeh, award winning photo",

    "Luxury": "baroque-style ({room}) with bath towel and plant and bathtub and bathroom sink with faucet and toilet seat and bathroom cabinet and shower and mirror. with intricate carvings and ornaments and dynamism and emotional exuberance and movement and drama and expensive and plush flooring and crystal and glass accents and twisted columns. cinematic photo, highly detailed, cinematic lighting, ultra-detailed, ultrarealistic, photorealism, 8k. baroque interior design style. masterpiece, cinematic light, ultrarealistic+, photorealistic+, 8k, raw photo, realistic, sharp focus on eyes, (symmetrical eyes), (intact eyes), hyperrealistic, highest quality, best quality, highly detailed, masterpiece, best quality, extremely detailed 8k wallpaper, ultra-detailed, best shadow, detailed background, detailed face, detailed eyes, high contrast, best illumination, dulux, caustic, dynamic angle, detailed glow, dramatic lighting, insanely detailed hair, symmetrical, professionally retouched, strong bokeh, award winning photo"
}
